<template>
    <table>
        <tr>
            <td><Piece></Piece></td>
            <td><Piece></Piece></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td><Piece></Piece></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </table>
</template>
<script>
import { Component, Prop, Vue } from 'vue-property-decorator'
import Piece from './Piece.vue'

@Component({
  components: {
    Piece,
  }
})
export default class Board extends Vue{
}
</script>
